name: Trigger All Release Combinations

on:
  workflow_dispatch:

jobs:
  trigger-combinations:
    strategy:
      max-parallel: 1
      matrix:
        forceClientAutoUpdate: [true, false]
        buildClient: 
          - Build only on macOS
          - Build only on Windows
          - Build on both macOS and Windows
        buildServer:
          - Build only on macOS
          - Build only on Windows
          - Build on both macOS and Windows

    runs-on: [self-hosted, linux]

    steps:
      - name: Call the release workflow
        uses: ./.github/workflows/build-executable.yml
        with:
          mode: patch
          forceClientAutoUpdate: ${{ matrix.forceClientAutoUpdate }}
          buildClient: ${{ matrix.buildClient }}
          buildServer: ${{ matrix.buildServer }}
